name: robotic_arm_app
description: robotic arm control.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  bloc: ^8.1.4
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  three_js: ^0.0.7
  three_js_helpers: ^0.0.5
  # plane_geometry: ^0.0.3
  flutter_gl: ^0.0.21
  flutter_ai_toolkit: ^0.10.0
  google_generative_ai: ^0.4.7
  firebase_core: ^4.2.0
  sliding_up_panel: ^2.0.0
  cupertino_icons: ^1.0.0
  flutter_bloc: ^8.1.6
  auto_route: ^10.2.0
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  logger: ^2.6.2
  json_serializable: ^6.11.1
  json_annotation: ^4.9.0
  carousel_slider: ^5.1.1
  flutter_svg: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  model_viewer_plus: ^1.6.0
  webview_flutter: ^4.0.0
  auto_route_generator: ^10.1.0
  build_runner: ^2.5.4

flutter:
  uses-material-design: true
  assets:
    - assets/coin.glb
    - assets/dash.glb
    - assets/ground.glb
    - assets/sky_sphere.glb
    - assets/bottom_arm.glb
    - assets/center_arm.glb
    - assets/top_arm.glb
    - assets/cybergearmotor.stp.glb
    - assets/wallfall1.jpg
    - assets/zero.glb
    - assets/one.glb
    - assets/two.glb
    - assets/three.glb
    - assets/four.glb
    - assets/five.glb